<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DummyDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 1. Pegawai
        DB::table('pegawai')->insert([
            [
                'nip' => '197803152005011001',
                'nama' => 'Dr. Bambang Sutrisno',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1978-03-15',
                'tmt_cpns' => '2005-01-15',
                'tmt_pangkat' => '2020-04-01',
                'pangkat' => 'Pembina Tingkat I',
                'golongan' => 'IV/b',
                'nama_jabatan' => 'Kepala Biro',
                'tmt_jabatan' => '2022-01-01',
                'unit_kerja' => 'Biro Administrasi',
                'pendidikan_terakhir' => 'S3',
                'jurusan' => 'Administrasi Publik',
                'tempat_pendidikan' => 'Universitas Indonesia',
                'tahun_lulus' => 2003,
                'masa_kerja_tahun' => 19,
                'masa_kerja_bulan' => 0,
                'latihan_jabatan' => 'Diklat Kepemimpinan Tingkat II',
                'perkiraan_pensiun' => 2033,
                'status_kepegawaian' => 'PNS',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198204201988032001',
                'nama' => 'Ir. Siti Nurhaliza',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1982-04-20',
                'tmt_cpns' => '1988-03-20',
                'tmt_pangkat' => '2018-07-15',
                'pangkat' => 'Pembina',
                'golongan' => 'IV/a',
                'nama_jabatan' => 'Kepala Bidang',
                'tmt_jabatan' => '2021-06-01',
                'unit_kerja' => 'Bidang Program dan Evaluasi',
                'pendidikan_terakhir' => 'S2',
                'jurusan' => 'Teknik Sipil',
                'tempat_pendidikan' => 'ITB Bandung',
                'tahun_lulus' => 2006,
                'masa_kerja_tahun' => 18,
                'masa_kerja_bulan' => 6,
                'latihan_jabatan' => 'Diklat Kepemimpinan Tingkat III',
                'perkiraan_pensiun' => 2032,
                'status_kepegawaian' => 'PNS',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198501152010011001',
                'nama' => 'Budi Santoso, S.Kom',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1985-01-15',
                'tmt_cpns' => '2010-01-15',
                'tmt_pangkat' => '2021-03-01',
                'pangkat' => 'Penata',
                'golongan' => 'III/d',
                'nama_jabatan' => 'Staff',
                'tmt_jabatan' => '2020-01-01',
                'unit_kerja' => 'Bidang IT',
                'pendidikan_terakhir' => 'S1',
                'jurusan' => 'Teknik Informatika',
                'tempat_pendidikan' => 'Universitas Surabaya',
                'tahun_lulus' => 2007,
                'masa_kerja_tahun' => 14,
                'masa_kerja_bulan' => 0,
                'latihan_jabatan' => 'Diklat Fungsional IT',
                'perkiraan_pensiun' => 2027,
                'status_kepegawaian' => 'PNS',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198703102015021002',
                'nama' => 'Eka Putri Wijaya',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1987-03-10',
                'tmt_cpns' => '2015-02-01',
                'tmt_pangkat' => '2022-08-01',
                'pangkat' => 'Penata Muda',
                'golongan' => 'III/b',
                'nama_jabatan' => 'Analis',
                'tmt_jabatan' => '2019-06-01',
                'unit_kerja' => 'Bidang Perencanaan',
                'pendidikan_terakhir' => 'S1',
                'jurusan' => 'Perencanaan Pembangunan',
                'tempat_pendidikan' => 'UGM',
                'tahun_lulus' => 2009,
                'masa_kerja_tahun' => 9,
                'masa_kerja_bulan' => 4,
                'latihan_jabatan' => 'Diklat Analis Kebijakan',
                'perkiraan_pensiun' => 2024,
                'status_kepegawaian' => 'PPPK',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '199012251920023003',
                'nama' => 'Muhammad Rizki Pratama',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1990-12-25',
                'tmt_cpns' => '2019-12-15',
                'tmt_pangkat' => '2024-01-01',
                'pangkat' => 'Penata Muda Tingkat I',
                'golongan' => 'III/c',
                'nama_jabatan' => 'Operator',
                'tmt_jabatan' => '2022-03-01',
                'unit_kerja' => 'Bidang Administrasi Data',
                'pendidikan_terakhir' => 'S1',
                'jurusan' => 'Administrasi Negara',
                'tempat_pendidikan' => 'Universitas Sumatera Utara',
                'tahun_lulus' => 2012,
                'masa_kerja_tahun' => 4,
                'masa_kerja_bulan' => 1,
                'latihan_jabatan' => 'Diklat Operator Data',
                'perkiraan_pensiun' => 2025,
                'status_kepegawaian' => 'PPPK',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 2. Unit Kerja
        DB::table('unit_kerja')->insert([
            [
                'kode_unit' => 'BA',
                'nama_unit' => 'Biro Administrasi',
                'jenis_unit' => 'utama',
                'tahun' => 2026,
                'keterangan' => 'Biro yang menangani administrasi umum dan tata usaha',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_unit' => 'BPE',
                'nama_unit' => 'Bidang Program dan Evaluasi',
                'jenis_unit' => 'utama',
                'tahun' => 2026,
                'keterangan' => 'Bidang yang mengurus program, perencanaan dan evaluasi kegiatan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_unit' => 'BIT',
                'nama_unit' => 'Bidang IT',
                'jenis_unit' => 'pendukung',
                'tahun' => 2026,
                'keterangan' => 'Bidang yang menangani infrastruktur teknologi informasi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_unit' => 'BP',
                'nama_unit' => 'Bidang Perencanaan',
                'jenis_unit' => 'utama',
                'tahun' => 2026,
                'keterangan' => 'Bidang yang menangani perencanaan strategis',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_unit' => 'BAD',
                'nama_unit' => 'Bidang Administrasi Data',
                'jenis_unit' => 'pendukung',
                'tahun' => 2026,
                'keterangan' => 'Bidang yang mengelola data dan basis data organisasi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 3. Sub Unit Kerja
        DB::table('sub_unit_kerja')->insert([
            [
                'unit_kerja_id' => 1,
                'nama_sub_unit' => 'Bagian Tata Usaha',
                'fungsi' => 'Menangani tata usaha, administrasi umum, dan surat-menyurat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'unit_kerja_id' => 1,
                'nama_sub_unit' => 'Bagian Keuangan',
                'fungsi' => 'Mengelola keuangan, anggaran, dan gaji pegawai',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'unit_kerja_id' => 2,
                'nama_sub_unit' => 'Seksi Program',
                'fungsi' => 'Menyusun dan mengontrol program kegiatan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'unit_kerja_id' => 2,
                'nama_sub_unit' => 'Seksi Evaluasi',
                'fungsi' => 'Melakukan evaluasi terhadap pelaksanaan program',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'unit_kerja_id' => 3,
                'nama_sub_unit' => 'Seksi Infrastruktur',
                'fungsi' => 'Mengelola infrastruktur dan jaringan komputer',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 4. Users
        DB::table('users')->insert([
            [
                'id_pegawai' => 1,
                'email' => 'bambang.sutrisno@kemkominfo.go.id',
                'password' => bcrypt('password123'),
                'role' => 'admin',
                'last_login' => now(),
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pegawai' => 2,
                'email' => 'siti.nurhaliza@kemkominfo.go.id',
                'password' => bcrypt('password123'),
                'role' => 'kepala',
                'last_login' => now(),
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pegawai' => 3,
                'email' => 'budi.santoso@kemkominfo.go.id',
                'password' => bcrypt('password123'),
                'role' => 'operator',
                'last_login' => now()->subDay(),
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pegawai' => 4,
                'email' => 'eka.putri@kemkominfo.go.id',
                'password' => bcrypt('password123'),
                'role' => 'verifikator',
                'last_login' => now()->subDays(2),
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pegawai' => 5,
                'email' => 'rizki.pratama@kemkominfo.go.id',
                'password' => bcrypt('password123'),
                'role' => 'operator',
                'last_login' => now()->subDays(3),
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 5. Kegiatan
        DB::table('kegiatan')->insert([
            [
                'nama_kegiatan' => 'Pelatihan Dasar CPNS Angkatan I',
                'rincian_kegiatan' => 'Pelatihan dasar untuk CPNS angkatan I tahun 2025 meliputi materi etika, integritas, dan layanan publik',
                'dokumentasi_url' => 'https://api.example.com/dokumentasi/K001',
                'materi_url' => 'https://api.example.com/materi/K001',
                'panduan_url' => 'https://api.example.com/panduan/K001',
                'laporan_url' => 'https://api.example.com/laporan/K001',
                'surat_menyurat_url' => 'https://api.example.com/surat/K001',
                'tanggal_mulai' => '2025-02-01',
                'tanggal_selesai' => '2025-02-28',
                'lokasi' => 'Jakarta',
                'flyer' => 'https://api.example.com/flyer/K001.jpg',
                'peserta_ringkasan' => 'CPNS',
                'total_peserta' => 45,
                'metode_pembayaran' => 'tunai',
                'deskripsi' => 'Pelatihan komprehensif untuk CPNS baru dengan materi etika dan integritas',
                'metode_pelaksanaan' => 'hybrid',
                'status' => 'selesai',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_kegiatan' => 'Workshop Digital Marketing',
                'rincian_kegiatan' => 'Workshop tentang strategi digital marketing untuk meningkatkan engagement media sosial organisasi',
                'dokumentasi_url' => 'https://api.example.com/dokumentasi/K002',
                'materi_url' => 'https://api.example.com/materi/K002',
                'panduan_url' => 'https://api.example.com/panduan/K002',
                'laporan_url' => 'https://api.example.com/laporan/K002',
                'surat_menyurat_url' => 'https://api.example.com/surat/K002',
                'tanggal_mulai' => '2025-03-10',
                'tanggal_selesai' => '2025-03-12',
                'lokasi' => 'Bandung',
                'flyer' => 'https://api.example.com/flyer/K002.jpg',
                'peserta_ringkasan' => 'PNS',
                'total_peserta' => 30,
                'metode_pembayaran' => 'transfer',
                'deskripsi' => 'Workshop interaktif tentang tren marketing digital terkini',
                'metode_pelaksanaan' => 'luring',
                'status' => 'berjalan',
                'created_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_kegiatan' => 'Seminar Transformasi Digital',
                'rincian_kegiatan' => 'Seminar tentang transformasi digital dalam organisasi pemerintah',
                'dokumentasi_url' => 'https://api.example.com/dokumentasi/K003',
                'materi_url' => 'https://api.example.com/materi/K003',
                'panduan_url' => 'https://api.example.com/panduan/K003',
                'laporan_url' => 'https://api.example.com/laporan/K003',
                'surat_menyurat_url' => 'https://api.example.com/surat/K003',
                'tanggal_mulai' => '2026-02-15',
                'tanggal_selesai' => '2026-02-16',
                'lokasi' => 'Jakarta',
                'flyer' => 'https://api.example.com/flyer/K003.jpg',
                'peserta_ringkasan' => 'Pegawai Umum',
                'total_peserta' => 100,
                'metode_pembayaran' => 'transfer_dan_pulsa',
                'deskripsi' => 'Seminar dengan pembicara internasional tentang digital transformation',
                'metode_pelaksanaan' => 'hybrid',
                'status' => 'draft',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_kegiatan' => 'Pelatihan Customer Service Excellence',
                'rincian_kegiatan' => 'Pelatihan untuk meningkatkan kualitas layanan pelanggan',
                'dokumentasi_url' => 'https://api.example.com/dokumentasi/K004',
                'materi_url' => 'https://api.example.com/materi/K004',
                'panduan_url' => 'https://api.example.com/panduan/K004',
                'laporan_url' => 'https://api.example.com/laporan/K004',
                'surat_menyurat_url' => 'https://api.example.com/surat/K004',
                'tanggal_mulai' => '2026-04-01',
                'tanggal_selesai' => '2026-04-03',
                'lokasi' => 'Surabaya',
                'flyer' => 'https://api.example.com/flyer/K004.jpg',
                'peserta_ringkasan' => 'Staff Layanan',
                'total_peserta' => 40,
                'metode_pembayaran' => 'pulsa',
                'deskripsi' => 'Pelatihan intensif tentang customer service terbaik',
                'metode_pelaksanaan' => 'luring',
                'status' => 'draft',
                'created_by' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_kegiatan' => 'Forum Diskusi Kebijakan Publik',
                'rincian_kegiatan' => 'Forum diskusi tentang kebijakan publik dan dampaknya terhadap masyarakat',
                'dokumentasi_url' => 'https://api.example.com/dokumentasi/K005',
                'materi_url' => 'https://api.example.com/materi/K005',
                'panduan_url' => 'https://api.example.com/panduan/K005',
                'laporan_url' => 'https://api.example.com/laporan/K005',
                'surat_menyurat_url' => 'https://api.example.com/surat/K005',
                'tanggal_mulai' => '2026-05-20',
                'tanggal_selesai' => '2026-05-21',
                'lokasi' => 'Yogyakarta',
                'flyer' => 'https://api.example.com/flyer/K005.jpg',
                'peserta_ringkasan' => 'Analis Kebijakan',
                'total_peserta' => 35,
                'metode_pembayaran' => 'tidak_dibayar',
                'deskripsi' => 'Forum terbuka untuk berbagi pemikiran tentang kebijakan publik',
                'metode_pelaksanaan' => 'daring',
                'status' => 'draft',
                'created_by' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 6. Surat Tugas
        DB::table('surat_tugas')->insert([
            [
                'id_kegiatan' => 1,
                'nomor_surat' => 'ST-001/2025',
                'tanggal_surat' => '2025-01-25',
                'id_penandatangan' => 1,
                'status' => 'diterbitkan',
                'file_surat' => 'https://api.example.com/surat-tugas/ST-001-2025.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kegiatan' => 2,
                'nomor_surat' => 'ST-002/2025',
                'tanggal_surat' => '2025-03-05',
                'id_penandatangan' => 2,
                'status' => 'diterbitkan',
                'file_surat' => 'https://api.example.com/surat-tugas/ST-002-2025.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kegiatan' => 3,
                'nomor_surat' => 'ST-003/2026',
                'tanggal_surat' => '2026-02-10',
                'id_penandatangan' => 1,
                'status' => 'draft',
                'file_surat' => 'https://api.example.com/surat-tugas/ST-003-2026.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kegiatan' => 4,
                'nomor_surat' => 'ST-004/2026',
                'tanggal_surat' => '2026-03-25',
                'id_penandatangan' => 2,
                'status' => 'draft',
                'file_surat' => 'https://api.example.com/surat-tugas/ST-004-2026.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kegiatan' => 5,
                'nomor_surat' => 'ST-005/2026',
                'tanggal_surat' => '2026-05-15',
                'id_penandatangan' => 1,
                'status' => 'dibatalkan',
                'file_surat' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 7. Surat Tugas Pegawai
        DB::table('surat_tugas_pegawai')->insert([
            [
                'id_surat_tugas' => 1,
                'id_pegawai' => 1,
                'peran' => 'penanggung_jawab',
            ],
            [
                'id_surat_tugas' => 1,
                'id_pegawai' => 2,
                'peran' => 'ketua_panitia',
            ],
            [
                'id_surat_tugas' => 2,
                'id_pegawai' => 3,
                'peran' => 'panitia',
            ],
            [
                'id_surat_tugas' => 3,
                'id_pegawai' => 4,
                'peran' => 'narasumber',
            ],
            [
                'id_surat_tugas' => 4,
                'id_pegawai' => 5,
                'peran' => 'peserta',
            ],
        ]);

        // 8. Peserta
        DB::table('peserta')->insert([
            [
                'id_kegiatan' => 1,
                'nama_lengkap' => 'Budi Santoso',
                'nip' => '198501152010011001',
                'pangkat' => 'Penata Muda',
                'gol' => 'III/a',
                'jabatan' => 'Staff',
                'no_hp' => '081234567890',
                'email' => 'budi.santoso@kemkominfo.go.id',
                'npwp_nik' => '1985011500000001',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1985-01-15',
                'jenis_kelamin' => 'Laki-laki',
                'nama_instansi' => 'Kemkominfo',
                'alamat_instansi' => 'Jl. Medan Merdeka Barat No.9, Jakarta Pusat',
                'kab_kota' => 'Jakarta Pusat',
                'provinsi' => 'DKI Jakarta',
                'telp_instansi' => '02134819000',
                'email_instansi' => 'info@kemkominfo.go.id',
                'provider_pulsa' => null,
                'nomor_rekening' => '1234567890',
                'nama_bank' => 'Bank Mandiri',
                'no_surat_tugas' => 'ST-001/2025',
                'tanggal_surat_tugas' => '2025-02-01',
                'peran' => 'Peserta',
                'tanda_tangan' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kegiatan' => 1,
                'nama_lengkap' => 'Sri Rahayuni',
                'nip' => '197909201995032002',
                'pangkat' => 'Penata',
                'gol' => 'III/c',
                'jabatan' => 'Analis',
                'no_hp' => '082345678901',
                'email' => 'sri.rahayuni@kemkominfo.go.id',
                'npwp_nik' => '1979092000000002',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1979-09-20',
                'jenis_kelamin' => 'Perempuan',
                'nama_instansi' => 'Kemkominfo',
                'alamat_instansi' => 'Jl. Medan Merdeka Barat No.9, Jakarta Pusat',
                'kab_kota' => 'Jakarta Pusat',
                'provinsi' => 'DKI Jakarta',
                'telp_instansi' => '02134819000',
                'email_instansi' => 'info@kemkominfo.go.id',
                'provider_pulsa' => 'Telkomsel',
                'nomor_rekening' => '2345678901',
                'nama_bank' => 'Bank BRI',
                'no_surat_tugas' => 'ST-001/2025',
                'tanggal_surat_tugas' => '2025-02-01',
                'peran' => 'Peserta',
                'tanda_tangan' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kegiatan' => 2,
                'nama_lengkap' => 'Ahmad Hidayat',
                'nip' => '198102101998021003',
                'pangkat' => 'Penata Muda Tingkat I',
                'gol' => 'III/b',
                'jabatan' => 'Operator',
                'no_hp' => '083456789012',
                'email' => 'ahmad.hidayat@kemkominfo.go.id',
                'npwp_nik' => '1981021000000003',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1981-02-10',
                'jenis_kelamin' => 'Laki-laki',
                'nama_instansi' => 'Kemkominfo',
                'alamat_instansi' => 'Jl. Medan Merdeka Barat No.9, Jakarta Pusat',
                'kab_kota' => 'Jakarta Pusat',
                'provinsi' => 'DKI Jakarta',
                'telp_instansi' => '02134819000',
                'email_instansi' => 'info@kemkominfo.go.id',
                'provider_pulsa' => 'Indosat',
                'nomor_rekening' => '3456789012',
                'nama_bank' => 'Bank BCA',
                'no_surat_tugas' => 'ST-002/2025',
                'tanggal_surat_tugas' => '2025-03-10',
                'peran' => 'Peserta',
                'tanda_tangan' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kegiatan' => 3,
                'nama_lengkap' => 'Dewi Lestari',
                'nip' => '198403151999012004',
                'pangkat' => 'Penata',
                'gol' => 'III/c',
                'jabatan' => 'Koordinator',
                'no_hp' => '084567890123',
                'email' => 'dewi.lestari@kemkominfo.go.id',
                'npwp_nik' => '1984031500000004',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1984-03-15',
                'jenis_kelamin' => 'Perempuan',
                'nama_instansi' => 'Kemkominfo',
                'alamat_instansi' => 'Jl. Medan Merdeka Barat No.9, Jakarta Pusat',
                'kab_kota' => 'Jakarta Pusat',
                'provinsi' => 'DKI Jakarta',
                'telp_instansi' => '02134819000',
                'email_instansi' => 'info@kemkominfo.go.id',
                'provider_pulsa' => null,
                'nomor_rekening' => '4567890123',
                'nama_bank' => 'Bank Mandiri',
                'no_surat_tugas' => 'ST-003/2026',
                'tanggal_surat_tugas' => '2026-02-15',
                'peran' => 'Peserta',
                'tanda_tangan' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kegiatan' => 4,
                'nama_lengkap' => 'Hendri Gunawan',
                'nip' => '198605271997022005',
                'pangkat' => 'Penata Muda',
                'gol' => 'III/a',
                'jabatan' => 'Staff',
                'no_hp' => '085678901234',
                'email' => 'hendri.gunawan@kemkominfo.go.id',
                'npwp_nik' => '1986052700000005',
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '1986-05-27',
                'jenis_kelamin' => 'Laki-laki',
                'nama_instansi' => 'Kemkominfo',
                'alamat_instansi' => 'Jl. Medan Merdeka Barat No.9, Jakarta Pusat',
                'kab_kota' => 'Jakarta Pusat',
                'provinsi' => 'DKI Jakarta',
                'telp_instansi' => '02134819000',
                'email_instansi' => 'info@kemkominfo.go.id',
                'provider_pulsa' => 'XL Axiata',
                'nomor_rekening' => '5678901234',
                'nama_bank' => 'Bank CIMB',
                'no_surat_tugas' => 'ST-004/2026',
                'tanggal_surat_tugas' => '2026-04-01',
                'peran' => 'Peserta',
                'tanda_tangan' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 9. Akun Peserta
        DB::table('akun_peserta')->insert([
            [
                'id_peserta' => 1,
                'username' => 'budi_santoso',
                'password' => bcrypt('password123'),
                'last_login' => now()->subDays(3),
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_peserta' => 2,
                'username' => 'sri_rahayuni',
                'password' => bcrypt('password123'),
                'last_login' => now()->subDays(4),
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_peserta' => 3,
                'username' => 'ahmad_hidayat',
                'password' => bcrypt('password123'),
                'last_login' => now()->subDays(5),
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_peserta' => 4,
                'username' => 'dewi_lestari',
                'password' => bcrypt('password123'),
                'last_login' => null,
                'status' => 'nonaktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_peserta' => 5,
                'username' => 'hendri_gunawan',
                'password' => bcrypt('password123'),
                'last_login' => now()->subDays(6),
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 10. Sertifikat
        DB::table('sertifikat')->insert([
            [
                'id_kegiatan' => 1,
                'id_peserta' => 1,
                'nomor_sertifikat' => 'CERT-2025-001',
                'tanggal_ttd' => '2025-02-28',
                'id_penandatangan' => 1,
                'template' => 'template_1',
                'peran' => 'Peserta',
                'status' => 'terbit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kegiatan' => 1,
                'id_peserta' => 2,
                'nomor_sertifikat' => 'CERT-2025-002',
                'tanggal_ttd' => '2025-02-28',
                'id_penandatangan' => 1,
                'template' => 'template_1',
                'peran' => 'Peserta',
                'status' => 'terbit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kegiatan' => 2,
                'id_peserta' => 3,
                'nomor_sertifikat' => 'CERT-2025-003',
                'tanggal_ttd' => '2025-03-15',
                'id_penandatangan' => 2,
                'template' => 'template_2',
                'peran' => 'Peserta',
                'status' => 'terbit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kegiatan' => 3,
                'id_peserta' => 4,
                'nomor_sertifikat' => 'CERT-2026-001',
                'tanggal_ttd' => null,
                'id_penandatangan' => 1,
                'template' => 'template_1',
                'peran' => 'Peserta',
                'status' => 'draft',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kegiatan' => 4,
                'id_peserta' => 5,
                'nomor_sertifikat' => 'CERT-2026-002',
                'tanggal_ttd' => null,
                'id_penandatangan' => 2,
                'template' => 'template_2',
                'peran' => 'Peserta',
                'status' => 'draft',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 11. Log Aktivitas
        DB::table('log_aktivitas')->insert([
            [
                'id_user' => 1,
                'aktivitas' => 'Membuat kegiatan baru: Pelatihan Dasar CPNS Angkatan I',
                'tabel' => 'kegiatan',
                'id_referensi' => 1,
                'created_at' => now()->subDays(20),
            ],
            [
                'id_user' => 2,
                'aktivitas' => 'Menerbitkan surat tugas: ST-001/2025',
                'tabel' => 'surat_tugas',
                'id_referensi' => 1,
                'created_at' => now()->subDays(15),
            ],
            [
                'id_user' => 3,
                'aktivitas' => 'Menambahkan peserta baru: Budi Santoso',
                'tabel' => 'peserta',
                'id_referensi' => 1,
                'created_at' => now()->subDays(10),
            ],
            [
                'id_user' => 1,
                'aktivitas' => 'Membuat sertifikat untuk peserta: Budi Santoso',
                'tabel' => 'sertifikat',
                'id_referensi' => 1,
                'created_at' => now()->subDays(5),
            ],
            [
                'id_user' => 4,
                'aktivitas' => 'Verifikasi data peserta',
                'tabel' => 'peserta',
                'id_referensi' => 2,
                'created_at' => now()->subDays(1),
            ],
        ]);

        // 12. Keanggotan Tim
        DB::table('keanggotan_tim')->insert([
            [
                'id_pegawai' => 1,
                'unit_kerja_id' => 1,
                'sub_unit_kerja_id' => 1,
                'peran' => 'Kepala',
                'tahun' => 2026,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pegawai' => 2,
                'unit_kerja_id' => 2,
                'sub_unit_kerja_id' => 3,
                'peran' => 'Ketua',
                'tahun' => 2026,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pegawai' => 3,
                'unit_kerja_id' => 3,
                'sub_unit_kerja_id' => 5,
                'peran' => 'Anggota',
                'tahun' => 2026,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pegawai' => 4,
                'unit_kerja_id' => 2,
                'sub_unit_kerja_id' => 4,
                'peran' => 'Anggota',
                'tahun' => 2026,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pegawai' => 5,
                'unit_kerja_id' => 5,
                'sub_unit_kerja_id' => null,
                'peran' => 'Anggota',
                'tahun' => 2026,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
